#![allow(clippy::missing_safety_doc, non_upper_case_globals)]

use error::Error;
use std::ffi::OsStr;
use std::os::windows::ffi::OsStrExt;
use std::os::windows::raw::HANDLE;
use windows_sys::Win32::Foundation::{
    ERROR_AUTODATASEG_EXCEEDS_64k, ERROR_ITERATED_DATA_EXCEEDS_64k, ERROR_ACCESS_DENIED,
    ERROR_ADAP_HDW_ERR, ERROR_ALREADY_ASSIGNED, ERROR_ALREADY_EXISTS, ERROR_ARENA_TRASHED,
    ERROR_ATOMIC_LOCKS_NOT_SUPPORTED, ERROR_BAD_ARGUMENTS, ERROR_BAD_COMMAND,
    ERROR_BAD_DEVICE_PATH, ERROR_BAD_DEV_TYPE, ERROR_BAD_DRIVER_LEVEL, ERROR_BAD_ENVIRONMENT,
    ERROR_BAD_EXE_FORMAT, ERROR_BAD_FILE_TYPE, ERROR_BAD_FORMAT, ERROR_BAD_LENGTH,
    ERROR_BAD_NETPATH, ERROR_BAD_NET_NAME, ERROR_BAD_NET_RESP, ERROR_BAD_PATHNAME, ERROR_BAD_PIPE,
    ERROR_BAD_REM_ADAP, ERROR_BAD_THREADID_ADDR, ERROR_BAD_UNIT, ERROR_BROKEN_PIPE,
    ERROR_BUFFER_OVERFLOW, ERROR_BUSY, ERROR_BUSY_DRIVE, ERROR_CALL_NOT_IMPLEMENTED,
    ERROR_CANCEL_VIOLATION, ERROR_CANNOT_COPY, ERROR_CANNOT_MAKE, ERROR_CHECKOUT_REQUIRED,
    ERROR_CHILD_NOT_COMPLETE, ERROR_COMPRESSED_FILE_NOT_SUPPORTED, ERROR_CRC,
    ERROR_CURRENT_DIRECTORY, ERROR_DATA_CHECKSUM_ERROR, ERROR_DELETE_PENDING,
    ERROR_DEVICE_FEATURE_NOT_SUPPORTED, ERROR_DEVICE_NO_RESOURCES,
    ERROR_DEVICE_SUPPORT_IN_PROGRESS, ERROR_DEVICE_UNREACHABLE, ERROR_DEV_NOT_EXIST,
    ERROR_DIRECTORY, ERROR_DIRECTORY_NOT_SUPPORTED, ERROR_DIRECT_ACCESS_HANDLE,
    ERROR_DIR_NOT_EMPTY, ERROR_DIR_NOT_ROOT, ERROR_DISCARDED, ERROR_DISK_CHANGE, ERROR_DISK_FULL,
    ERROR_DISK_RESOURCES_EXHAUSTED, ERROR_DISK_TOO_FRAGMENTED, ERROR_DRIVE_LOCKED,
    ERROR_DUPLICATE_PRIVILEGES, ERROR_DUP_NAME, ERROR_DYNLINK_FROM_INVALID_RING,
    ERROR_EAS_DIDNT_FIT, ERROR_EAS_NOT_SUPPORTED, ERROR_EA_FILE_CORRUPT,
    ERROR_EA_LIST_INCONSISTENT, ERROR_EA_TABLE_FULL, ERROR_ENVVAR_NOT_FOUND,
    ERROR_EXCL_SEM_ALREADY_OWNED, ERROR_EXE_CANNOT_MODIFY_SIGNED_BINARY,
    ERROR_EXE_CANNOT_MODIFY_STRONG_SIGNED_BINARY, ERROR_EXE_MACHINE_TYPE_MISMATCH,
    ERROR_EXE_MARKED_INVALID, ERROR_FAIL_I24, ERROR_FAIL_NOACTION_REBOOT, ERROR_FAIL_RESTART,
    ERROR_FAIL_SHUTDOWN, ERROR_FILENAME_EXCED_RANGE, ERROR_FILE_CHECKED_OUT, ERROR_FILE_EXISTS,
    ERROR_FILE_LEVEL_TRIM_NOT_SUPPORTED, ERROR_FILE_NOT_FOUND, ERROR_FILE_TOO_LARGE,
    ERROR_FORMS_AUTH_REQUIRED, ERROR_GEN_FAILURE, ERROR_HANDLE_DISK_FULL, ERROR_HANDLE_EOF,
    ERROR_IMAGE_SUBSYSTEM_NOT_PRESENT, ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING,
    ERROR_INFLOOP_IN_RELOC_CHAIN, ERROR_INSUFFICIENT_BUFFER, ERROR_INTERMIXED_KERNEL_EA_OPERATION,
    ERROR_INVALID_ACCESS, ERROR_INVALID_ADDRESS, ERROR_INVALID_AT_INTERRUPT_TIME,
    ERROR_INVALID_BLOCK, ERROR_INVALID_CAP, ERROR_INVALID_CATEGORY, ERROR_INVALID_DATA,
    ERROR_INVALID_DRIVE, ERROR_INVALID_EA_HANDLE, ERROR_INVALID_EA_NAME, ERROR_INVALID_EVENT_COUNT,
    ERROR_INVALID_EXCEPTION_HANDLER, ERROR_INVALID_EXE_SIGNATURE,
    ERROR_INVALID_FIELD_IN_PARAMETER_LIST, ERROR_INVALID_FLAG_NUMBER, ERROR_INVALID_FUNCTION,
    ERROR_INVALID_HANDLE, ERROR_INVALID_LEVEL, ERROR_INVALID_LIST_FORMAT, ERROR_INVALID_LOCK_RANGE,
    ERROR_INVALID_MINALLOCSIZE, ERROR_INVALID_MODULETYPE, ERROR_INVALID_NAME,
    ERROR_INVALID_OPLOCK_PROTOCOL, ERROR_INVALID_ORDINAL, ERROR_INVALID_PARAMETER,
    ERROR_INVALID_PASSWORD, ERROR_INVALID_SEGDPL, ERROR_INVALID_SEGMENT_NUMBER,
    ERROR_INVALID_SIGNAL_NUMBER, ERROR_INVALID_STACKSEG, ERROR_INVALID_STARTING_CODESEG,
    ERROR_INVALID_TARGET_HANDLE, ERROR_INVALID_TOKEN, ERROR_INVALID_VERIFY_SWITCH,
    ERROR_IOPL_NOT_ENABLED, ERROR_IS_JOINED, ERROR_IS_JOIN_PATH, ERROR_IS_JOIN_TARGET,
    ERROR_IS_SUBSTED, ERROR_IS_SUBST_PATH, ERROR_IS_SUBST_TARGET, ERROR_JOIN_TO_JOIN,
    ERROR_JOIN_TO_SUBST, ERROR_LABEL_TOO_LONG, ERROR_LOCKED, ERROR_LOCK_FAILED,
    ERROR_LOCK_VIOLATION, ERROR_MAX_SESSIONS_REACHED, ERROR_MAX_THRDS_REACHED,
    ERROR_META_EXPANSION_TOO_LONG, ERROR_MOD_NOT_FOUND, ERROR_MORE_DATA, ERROR_MR_MID_NOT_FOUND,
    ERROR_NEGATIVE_SEEK, ERROR_NESTING_NOT_ALLOWED, ERROR_NETNAME_DELETED,
    ERROR_NETWORK_ACCESS_DENIED, ERROR_NETWORK_BUSY, ERROR_NET_WRITE_FAULT,
    ERROR_NOTIFICATION_GUID_ALREADY_DEFINED, ERROR_NOT_ALLOWED_ON_SYSTEM_FILE, ERROR_NOT_DOS_DISK,
    ERROR_NOT_ENOUGH_MEMORY, ERROR_NOT_JOINED, ERROR_NOT_LOCKED, ERROR_NOT_OWNER, ERROR_NOT_READY,
    ERROR_NOT_READ_FROM_COPY, ERROR_NOT_REDUNDANT_STORAGE, ERROR_NOT_SAME_DEVICE,
    ERROR_NOT_SUBSTED, ERROR_NOT_SUPPORTED, ERROR_NO_DATA, ERROR_NO_MORE_FILES,
    ERROR_NO_MORE_ITEMS, ERROR_NO_MORE_SEARCH_HANDLES, ERROR_NO_PROC_SLOTS,
    ERROR_NO_RANGES_PROCESSED, ERROR_NO_SIGNAL_SENT, ERROR_NO_SPOOL_SPACE, ERROR_NO_VOLUME_LABEL,
    ERROR_OFFSET_ALIGNMENT_VIOLATION, ERROR_OPEN_FAILED, ERROR_OPERATION_IN_PROGRESS,
    ERROR_OPLOCK_NOT_GRANTED, ERROR_OUTOFMEMORY, ERROR_OUT_OF_PAPER, ERROR_OUT_OF_STRUCTURES,
    ERROR_PARTIAL_COPY, ERROR_PATH_BUSY, ERROR_PATH_NOT_FOUND, ERROR_PIPE_BUSY, ERROR_PIPE_LOCAL,
    ERROR_PIPE_NOT_CONNECTED, ERROR_PRINTQ_FULL, ERROR_PRINT_CANCELLED,
    ERROR_PROCESS_MODE_ALREADY_BACKGROUND, ERROR_PROCESS_MODE_NOT_BACKGROUND, ERROR_PROC_NOT_FOUND,
    ERROR_READ_FAULT, ERROR_REDIR_PAUSED, ERROR_RELOC_CHAIN_XEEDS_SEGLIM, ERROR_REM_NOT_LIST,
    ERROR_REQ_NOT_ACCEP, ERROR_RESIDENT_FILE_NOT_SUPPORTED, ERROR_RING2SEG_MUST_BE_MOVABLE,
    ERROR_RING2_STACK_IN_USE, ERROR_SAME_DRIVE, ERROR_SCOPE_NOT_FOUND, ERROR_SCRUB_DATA_DISABLED,
    ERROR_SECTOR_NOT_FOUND, ERROR_SECURITY_STREAM_IS_INCONSISTENT, ERROR_SEEK,
    ERROR_SEEK_ON_DEVICE, ERROR_SEM_IS_SET, ERROR_SEM_NOT_FOUND, ERROR_SEM_OWNER_DIED,
    ERROR_SEM_TIMEOUT, ERROR_SEM_USER_LIMIT, ERROR_SHARING_BUFFER_EXCEEDED, ERROR_SHARING_PAUSED,
    ERROR_SHARING_VIOLATION, ERROR_SHORT_NAMES_NOT_ENABLED_ON_VOLUME, ERROR_SIGNAL_PENDING,
    ERROR_SIGNAL_REFUSED, ERROR_SUBST_TO_JOIN, ERROR_SUBST_TO_SUBST, ERROR_SUCCESS,
    ERROR_SYSTEM_TRACE, ERROR_THREAD_1_INACTIVE, ERROR_THREAD_MODE_ALREADY_BACKGROUND,
    ERROR_THREAD_MODE_NOT_BACKGROUND, ERROR_TOO_MANY_CMDS, ERROR_TOO_MANY_DESCRIPTORS,
    ERROR_TOO_MANY_MODULES, ERROR_TOO_MANY_MUXWAITERS, ERROR_TOO_MANY_NAMES,
    ERROR_TOO_MANY_OPEN_FILES, ERROR_TOO_MANY_POSTS, ERROR_TOO_MANY_SEMAPHORES,
    ERROR_TOO_MANY_SEM_REQUESTS, ERROR_TOO_MANY_SESS, ERROR_TOO_MANY_TCBS, ERROR_UNDEFINED_SCOPE,
    ERROR_UNEXP_NET_ERR, ERROR_VC_DISCONNECTED, ERROR_VIRUS_DELETED, ERROR_VIRUS_INFECTED,
    ERROR_WAIT_NO_CHILDREN, ERROR_WRITE_FAULT, ERROR_WRITE_PROTECT, ERROR_WRONG_DISK, WAIT_TIMEOUT,
};
use windows_sys::Win32::Storage::Vhd::{
    AttachVirtualDisk, OpenVirtualDisk, ATTACH_VIRTUAL_DISK_FLAG_PERMANENT_LIFETIME,
    ATTACH_VIRTUAL_DISK_FLAG_READ_ONLY, VIRTUAL_DISK_ACCESS_ATTACH_RO,
    VIRTUAL_DISK_ACCESS_ATTACH_RW, VIRTUAL_STORAGE_TYPE, VIRTUAL_STORAGE_TYPE_DEVICE_VHD,
    VIRTUAL_STORAGE_TYPE_DEVICE_VHDX, VIRTUAL_STORAGE_TYPE_VENDOR_MICROSOFT,
};

pub use error::Result;

mod error;

pub struct Vhd {
    path: Vec<u16>,
    handle: HANDLE,
    vhd_type: VhdType,
}

#[derive(Debug)]
pub enum MountMode {
    ReadOnly,
    ReadWrite,
}

#[derive(Debug)]
pub enum VhdType {
    Vhd,
    Vhdx,
}

impl Vhd {
    pub fn new<P: AsRef<OsStr>>(path: P, vhd_type: VhdType) -> Self {
        let wide_path: Vec<u16> = path.as_ref().encode_wide().chain(Some(0)).collect();

        Vhd {
            path: wide_path,
            handle: std::ptr::null_mut(),
            vhd_type,
        }
    }

    /// Mount the [`Vhd`] to a Windows device. Persistent will mount the [`Vhd`] until explicitly
    /// `unmounted` or the Windows system shuts down. Otherwise the mount lives until [`Vhd`] is
    /// dropped (tied to the handle).
    pub fn mount(&mut self, mode: MountMode, persistent: bool) -> Result<()> {
        let storage_type = VIRTUAL_STORAGE_TYPE {
            DeviceId: match self.vhd_type {
                VhdType::Vhd => VIRTUAL_STORAGE_TYPE_DEVICE_VHD,
                VhdType::Vhdx => VIRTUAL_STORAGE_TYPE_DEVICE_VHDX,
            },
            VendorId: VIRTUAL_STORAGE_TYPE_VENDOR_MICROSOFT,
        };

        let access = match mode {
            MountMode::ReadOnly => VIRTUAL_DISK_ACCESS_ATTACH_RO,
            MountMode::ReadWrite => VIRTUAL_DISK_ACCESS_ATTACH_RW,
        };

        let open_result = unsafe {
            OpenVirtualDisk(
                &storage_type,
                self.path.as_ptr(),
                access,
                0,
                std::ptr::null(),
                &mut self.handle,
            )
        };

        match open_result {
            ERROR_SUCCESS => {}
            e => return Err(map_win32_system_error_code(e)),
        };

        let mut flags = 0;

        if matches!(mode, MountMode::ReadOnly) {
            flags |= ATTACH_VIRTUAL_DISK_FLAG_READ_ONLY;
        }

        if persistent {
            flags |= ATTACH_VIRTUAL_DISK_FLAG_PERMANENT_LIFETIME;
        }

        let attach_result = unsafe {
            AttachVirtualDisk(
                self.handle,
                std::ptr::null_mut(),
                flags,
                0,
                std::ptr::null(),
                std::ptr::null(),
            )
        };

        match attach_result {
            ERROR_SUCCESS => Ok(()),
            e => Err(map_win32_system_error_code(e)),
        }
    }
}

// unfortunately we do not know which errors are relevant for OpenVirtualDisk and
// AttachVirtualDisk
// https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-
//
// TODO: add more known error codes. these are all from 0-499
fn map_win32_system_error_code(attach_result: u32) -> Error {
    match attach_result {
        ERROR_INVALID_FUNCTION => Error::ERROR_INVALID_FUNCTION,
        ERROR_FILE_NOT_FOUND => Error::ERROR_FILE_NOT_FOUND,
        ERROR_PATH_NOT_FOUND => Error::ERROR_PATH_NOT_FOUND,
        ERROR_TOO_MANY_OPEN_FILES => Error::ERROR_TOO_MANY_OPEN_FILES,
        ERROR_ACCESS_DENIED => Error::ERROR_ACCESS_DENIED,
        ERROR_INVALID_HANDLE => Error::ERROR_INVALID_HANDLE,
        ERROR_ARENA_TRASHED => Error::ERROR_ARENA_TRASHED,
        ERROR_NOT_ENOUGH_MEMORY => Error::ERROR_NOT_ENOUGH_MEMORY,
        ERROR_INVALID_BLOCK => Error::ERROR_INVALID_BLOCK,
        ERROR_BAD_ENVIRONMENT => Error::ERROR_BAD_ENVIRONMENT,
        ERROR_BAD_FORMAT => Error::ERROR_BAD_FORMAT,
        ERROR_INVALID_ACCESS => Error::ERROR_INVALID_ACCESS,
        ERROR_INVALID_DATA => Error::ERROR_INVALID_DATA,
        ERROR_OUTOFMEMORY => Error::ERROR_OUTOFMEMORY,
        ERROR_INVALID_DRIVE => Error::ERROR_INVALID_DRIVE,
        ERROR_CURRENT_DIRECTORY => Error::ERROR_CURRENT_DIRECTORY,
        ERROR_NOT_SAME_DEVICE => Error::ERROR_NOT_SAME_DEVICE,
        ERROR_NO_MORE_FILES => Error::ERROR_NO_MORE_FILES,
        ERROR_WRITE_PROTECT => Error::ERROR_WRITE_PROTECT,
        ERROR_BAD_UNIT => Error::ERROR_BAD_UNIT,
        ERROR_NOT_READY => Error::ERROR_NOT_READY,
        ERROR_BAD_COMMAND => Error::ERROR_BAD_COMMAND,
        ERROR_CRC => Error::ERROR_CRC,
        ERROR_BAD_LENGTH => Error::ERROR_BAD_LENGTH,
        ERROR_SEEK => Error::ERROR_SEEK,
        ERROR_NOT_DOS_DISK => Error::ERROR_NOT_DOS_DISK,
        ERROR_SECTOR_NOT_FOUND => Error::ERROR_SECTOR_NOT_FOUND,
        ERROR_OUT_OF_PAPER => Error::ERROR_OUT_OF_PAPER,
        ERROR_WRITE_FAULT => Error::ERROR_WRITE_FAULT,
        ERROR_READ_FAULT => Error::ERROR_READ_FAULT,
        ERROR_GEN_FAILURE => Error::ERROR_GEN_FAILURE,
        ERROR_SHARING_VIOLATION => Error::ERROR_SHARING_VIOLATION,
        ERROR_LOCK_VIOLATION => Error::ERROR_LOCK_VIOLATION,
        ERROR_WRONG_DISK => Error::ERROR_WRONG_DISK,
        ERROR_SHARING_BUFFER_EXCEEDED => Error::ERROR_SHARING_BUFFER_EXCEEDED,
        ERROR_HANDLE_EOF => Error::ERROR_HANDLE_EOF,
        ERROR_HANDLE_DISK_FULL => Error::ERROR_HANDLE_DISK_FULL,
        ERROR_NOT_SUPPORTED => Error::ERROR_NOT_SUPPORTED,
        ERROR_REM_NOT_LIST => Error::ERROR_REM_NOT_LIST,
        ERROR_DUP_NAME => Error::ERROR_DUP_NAME,
        ERROR_BAD_NETPATH => Error::ERROR_BAD_NETPATH,
        ERROR_NETWORK_BUSY => Error::ERROR_NETWORK_BUSY,
        ERROR_DEV_NOT_EXIST => Error::ERROR_DEV_NOT_EXIST,
        ERROR_TOO_MANY_CMDS => Error::ERROR_TOO_MANY_CMDS,
        ERROR_ADAP_HDW_ERR => Error::ERROR_ADAP_HDW_ERR,
        ERROR_BAD_NET_RESP => Error::ERROR_BAD_NET_RESP,
        ERROR_UNEXP_NET_ERR => Error::ERROR_UNEXP_NET_ERR,
        ERROR_BAD_REM_ADAP => Error::ERROR_BAD_REM_ADAP,
        ERROR_PRINTQ_FULL => Error::ERROR_PRINTQ_FULL,
        ERROR_NO_SPOOL_SPACE => Error::ERROR_NO_SPOOL_SPACE,
        ERROR_PRINT_CANCELLED => Error::ERROR_PRINT_CANCELLED,
        ERROR_NETNAME_DELETED => Error::ERROR_NETNAME_DELETED,
        ERROR_NETWORK_ACCESS_DENIED => Error::ERROR_NETWORK_ACCESS_DENIED,
        ERROR_BAD_DEV_TYPE => Error::ERROR_BAD_DEV_TYPE,
        ERROR_BAD_NET_NAME => Error::ERROR_BAD_NET_NAME,
        ERROR_TOO_MANY_NAMES => Error::ERROR_TOO_MANY_NAMES,
        ERROR_TOO_MANY_SESS => Error::ERROR_TOO_MANY_SESS,
        ERROR_SHARING_PAUSED => Error::ERROR_SHARING_PAUSED,
        ERROR_REQ_NOT_ACCEP => Error::ERROR_REQ_NOT_ACCEP,
        ERROR_REDIR_PAUSED => Error::ERROR_REDIR_PAUSED,
        ERROR_FILE_EXISTS => Error::ERROR_FILE_EXISTS,
        ERROR_CANNOT_MAKE => Error::ERROR_CANNOT_MAKE,
        ERROR_FAIL_I24 => Error::ERROR_FAIL_I24,
        ERROR_OUT_OF_STRUCTURES => Error::ERROR_OUT_OF_STRUCTURES,
        ERROR_ALREADY_ASSIGNED => Error::ERROR_ALREADY_ASSIGNED,
        ERROR_INVALID_PASSWORD => Error::ERROR_INVALID_PASSWORD,
        ERROR_INVALID_PARAMETER => Error::ERROR_INVALID_PARAMETER,
        ERROR_NET_WRITE_FAULT => Error::ERROR_NET_WRITE_FAULT,
        ERROR_NO_PROC_SLOTS => Error::ERROR_NO_PROC_SLOTS,
        ERROR_TOO_MANY_SEMAPHORES => Error::ERROR_TOO_MANY_SEMAPHORES,
        ERROR_EXCL_SEM_ALREADY_OWNED => Error::ERROR_EXCL_SEM_ALREADY_OWNED,
        ERROR_SEM_IS_SET => Error::ERROR_SEM_IS_SET,
        ERROR_TOO_MANY_SEM_REQUESTS => Error::ERROR_TOO_MANY_SEM_REQUESTS,
        ERROR_INVALID_AT_INTERRUPT_TIME => Error::ERROR_INVALID_AT_INTERRUPT_TIME,
        ERROR_SEM_OWNER_DIED => Error::ERROR_SEM_OWNER_DIED,
        ERROR_SEM_USER_LIMIT => Error::ERROR_SEM_USER_LIMIT,
        ERROR_DISK_CHANGE => Error::ERROR_DISK_CHANGE,
        ERROR_DRIVE_LOCKED => Error::ERROR_DRIVE_LOCKED,
        ERROR_BROKEN_PIPE => Error::ERROR_BROKEN_PIPE,
        ERROR_OPEN_FAILED => Error::ERROR_OPEN_FAILED,
        ERROR_BUFFER_OVERFLOW => Error::ERROR_BUFFER_OVERFLOW,
        ERROR_DISK_FULL => Error::ERROR_DISK_FULL,
        ERROR_NO_MORE_SEARCH_HANDLES => Error::ERROR_NO_MORE_SEARCH_HANDLES,
        ERROR_INVALID_TARGET_HANDLE => Error::ERROR_INVALID_TARGET_HANDLE,
        ERROR_INVALID_CATEGORY => Error::ERROR_INVALID_CATEGORY,
        ERROR_INVALID_VERIFY_SWITCH => Error::ERROR_INVALID_VERIFY_SWITCH,
        ERROR_BAD_DRIVER_LEVEL => Error::ERROR_BAD_DRIVER_LEVEL,
        ERROR_CALL_NOT_IMPLEMENTED => Error::ERROR_CALL_NOT_IMPLEMENTED,
        ERROR_SEM_TIMEOUT => Error::ERROR_SEM_TIMEOUT,
        ERROR_INSUFFICIENT_BUFFER => Error::ERROR_INSUFFICIENT_BUFFER,
        ERROR_INVALID_NAME => Error::ERROR_INVALID_NAME,
        ERROR_INVALID_LEVEL => Error::ERROR_INVALID_LEVEL,
        ERROR_NO_VOLUME_LABEL => Error::ERROR_NO_VOLUME_LABEL,
        ERROR_MOD_NOT_FOUND => Error::ERROR_MOD_NOT_FOUND,
        ERROR_PROC_NOT_FOUND => Error::ERROR_PROC_NOT_FOUND,
        ERROR_WAIT_NO_CHILDREN => Error::ERROR_WAIT_NO_CHILDREN,
        ERROR_CHILD_NOT_COMPLETE => Error::ERROR_CHILD_NOT_COMPLETE,
        ERROR_DIRECT_ACCESS_HANDLE => Error::ERROR_DIRECT_ACCESS_HANDLE,
        ERROR_NEGATIVE_SEEK => Error::ERROR_NEGATIVE_SEEK,
        ERROR_SEEK_ON_DEVICE => Error::ERROR_SEEK_ON_DEVICE,
        ERROR_IS_JOIN_TARGET => Error::ERROR_IS_JOIN_TARGET,
        ERROR_IS_JOINED => Error::ERROR_IS_JOINED,
        ERROR_IS_SUBSTED => Error::ERROR_IS_SUBSTED,
        ERROR_NOT_JOINED => Error::ERROR_NOT_JOINED,
        ERROR_NOT_SUBSTED => Error::ERROR_NOT_SUBSTED,
        ERROR_JOIN_TO_JOIN => Error::ERROR_JOIN_TO_JOIN,
        ERROR_SUBST_TO_SUBST => Error::ERROR_SUBST_TO_SUBST,
        ERROR_JOIN_TO_SUBST => Error::ERROR_JOIN_TO_SUBST,
        ERROR_SUBST_TO_JOIN => Error::ERROR_SUBST_TO_JOIN,
        ERROR_BUSY_DRIVE => Error::ERROR_BUSY_DRIVE,
        ERROR_SAME_DRIVE => Error::ERROR_SAME_DRIVE,
        ERROR_DIR_NOT_ROOT => Error::ERROR_DIR_NOT_ROOT,
        ERROR_DIR_NOT_EMPTY => Error::ERROR_DIR_NOT_EMPTY,
        ERROR_IS_SUBST_PATH => Error::ERROR_IS_SUBST_PATH,
        ERROR_IS_JOIN_PATH => Error::ERROR_IS_JOIN_PATH,
        ERROR_PATH_BUSY => Error::ERROR_PATH_BUSY,
        ERROR_IS_SUBST_TARGET => Error::ERROR_IS_SUBST_TARGET,
        ERROR_SYSTEM_TRACE => Error::ERROR_SYSTEM_TRACE,
        ERROR_INVALID_EVENT_COUNT => Error::ERROR_INVALID_EVENT_COUNT,
        ERROR_TOO_MANY_MUXWAITERS => Error::ERROR_TOO_MANY_MUXWAITERS,
        ERROR_INVALID_LIST_FORMAT => Error::ERROR_INVALID_LIST_FORMAT,
        ERROR_LABEL_TOO_LONG => Error::ERROR_LABEL_TOO_LONG,
        ERROR_TOO_MANY_TCBS => Error::ERROR_TOO_MANY_TCBS,
        ERROR_SIGNAL_REFUSED => Error::ERROR_SIGNAL_REFUSED,
        ERROR_DISCARDED => Error::ERROR_DISCARDED,
        ERROR_NOT_LOCKED => Error::ERROR_NOT_LOCKED,
        ERROR_BAD_THREADID_ADDR => Error::ERROR_BAD_THREADID_ADDR,
        ERROR_BAD_ARGUMENTS => Error::ERROR_BAD_ARGUMENTS,
        ERROR_BAD_PATHNAME => Error::ERROR_BAD_PATHNAME,
        ERROR_SIGNAL_PENDING => Error::ERROR_SIGNAL_PENDING,
        ERROR_MAX_THRDS_REACHED => Error::ERROR_MAX_THRDS_REACHED,
        ERROR_LOCK_FAILED => Error::ERROR_LOCK_FAILED,
        ERROR_BUSY => Error::ERROR_BUSY,
        ERROR_DEVICE_SUPPORT_IN_PROGRESS => Error::ERROR_DEVICE_SUPPORT_IN_PROGRESS,
        ERROR_CANCEL_VIOLATION => Error::ERROR_CANCEL_VIOLATION,
        ERROR_ATOMIC_LOCKS_NOT_SUPPORTED => Error::ERROR_ATOMIC_LOCKS_NOT_SUPPORTED,
        ERROR_INVALID_SEGMENT_NUMBER => Error::ERROR_INVALID_SEGMENT_NUMBER,
        ERROR_INVALID_ORDINAL => Error::ERROR_INVALID_ORDINAL,
        ERROR_ALREADY_EXISTS => Error::ERROR_ALREADY_EXISTS,
        ERROR_INVALID_FLAG_NUMBER => Error::ERROR_INVALID_FLAG_NUMBER,
        ERROR_SEM_NOT_FOUND => Error::ERROR_SEM_NOT_FOUND,
        ERROR_INVALID_STARTING_CODESEG => Error::ERROR_INVALID_STARTING_CODESEG,
        ERROR_INVALID_STACKSEG => Error::ERROR_INVALID_STACKSEG,
        ERROR_INVALID_MODULETYPE => Error::ERROR_INVALID_MODULETYPE,
        ERROR_INVALID_EXE_SIGNATURE => Error::ERROR_INVALID_EXE_SIGNATURE,
        ERROR_EXE_MARKED_INVALID => Error::ERROR_EXE_MARKED_INVALID,
        ERROR_BAD_EXE_FORMAT => Error::ERROR_BAD_EXE_FORMAT,
        ERROR_ITERATED_DATA_EXCEEDS_64k => Error::ERROR_ITERATED_DATA_EXCEEDS_64k,
        ERROR_INVALID_MINALLOCSIZE => Error::ERROR_INVALID_MINALLOCSIZE,
        ERROR_DYNLINK_FROM_INVALID_RING => Error::ERROR_DYNLINK_FROM_INVALID_RING,
        ERROR_IOPL_NOT_ENABLED => Error::ERROR_IOPL_NOT_ENABLED,
        ERROR_INVALID_SEGDPL => Error::ERROR_INVALID_SEGDPL,
        ERROR_AUTODATASEG_EXCEEDS_64k => Error::ERROR_AUTODATASEG_EXCEEDS_64k,
        ERROR_RING2SEG_MUST_BE_MOVABLE => Error::ERROR_RING2SEG_MUST_BE_MOVABLE,
        ERROR_RELOC_CHAIN_XEEDS_SEGLIM => Error::ERROR_RELOC_CHAIN_XEEDS_SEGLIM,
        ERROR_INFLOOP_IN_RELOC_CHAIN => Error::ERROR_INFLOOP_IN_RELOC_CHAIN,
        ERROR_ENVVAR_NOT_FOUND => Error::ERROR_ENVVAR_NOT_FOUND,
        ERROR_NO_SIGNAL_SENT => Error::ERROR_NO_SIGNAL_SENT,
        ERROR_FILENAME_EXCED_RANGE => Error::ERROR_FILENAME_EXCED_RANGE,
        ERROR_RING2_STACK_IN_USE => Error::ERROR_RING2_STACK_IN_USE,
        ERROR_META_EXPANSION_TOO_LONG => Error::ERROR_META_EXPANSION_TOO_LONG,
        ERROR_INVALID_SIGNAL_NUMBER => Error::ERROR_INVALID_SIGNAL_NUMBER,
        ERROR_THREAD_1_INACTIVE => Error::ERROR_THREAD_1_INACTIVE,
        ERROR_LOCKED => Error::ERROR_LOCKED,
        ERROR_TOO_MANY_MODULES => Error::ERROR_TOO_MANY_MODULES,
        ERROR_NESTING_NOT_ALLOWED => Error::ERROR_NESTING_NOT_ALLOWED,
        ERROR_EXE_MACHINE_TYPE_MISMATCH => Error::ERROR_EXE_MACHINE_TYPE_MISMATCH,
        ERROR_EXE_CANNOT_MODIFY_SIGNED_BINARY => Error::ERROR_EXE_CANNOT_MODIFY_SIGNED_BINARY,
        ERROR_EXE_CANNOT_MODIFY_STRONG_SIGNED_BINARY => {
            Error::ERROR_EXE_CANNOT_MODIFY_STRONG_SIGNED_BINARY
        }
        ERROR_FILE_CHECKED_OUT => Error::ERROR_FILE_CHECKED_OUT,
        ERROR_CHECKOUT_REQUIRED => Error::ERROR_CHECKOUT_REQUIRED,
        ERROR_BAD_FILE_TYPE => Error::ERROR_BAD_FILE_TYPE,
        ERROR_FILE_TOO_LARGE => Error::ERROR_FILE_TOO_LARGE,
        ERROR_FORMS_AUTH_REQUIRED => Error::ERROR_FORMS_AUTH_REQUIRED,
        ERROR_VIRUS_INFECTED => Error::ERROR_VIRUS_INFECTED,
        ERROR_VIRUS_DELETED => Error::ERROR_VIRUS_DELETED,
        ERROR_PIPE_LOCAL => Error::ERROR_PIPE_LOCAL,
        ERROR_BAD_PIPE => Error::ERROR_BAD_PIPE,
        ERROR_PIPE_BUSY => Error::ERROR_PIPE_BUSY,
        ERROR_NO_DATA => Error::ERROR_NO_DATA,
        ERROR_PIPE_NOT_CONNECTED => Error::ERROR_PIPE_NOT_CONNECTED,
        ERROR_MORE_DATA => Error::ERROR_MORE_DATA,
        ERROR_VC_DISCONNECTED => Error::ERROR_VC_DISCONNECTED,
        ERROR_INVALID_EA_NAME => Error::ERROR_INVALID_EA_NAME,
        ERROR_EA_LIST_INCONSISTENT => Error::ERROR_EA_LIST_INCONSISTENT,
        WAIT_TIMEOUT => Error::WAIT_TIMEOUT,
        ERROR_NO_MORE_ITEMS => Error::ERROR_NO_MORE_ITEMS,
        ERROR_CANNOT_COPY => Error::ERROR_CANNOT_COPY,
        ERROR_DIRECTORY => Error::ERROR_DIRECTORY,
        ERROR_EAS_DIDNT_FIT => Error::ERROR_EAS_DIDNT_FIT,
        ERROR_EA_FILE_CORRUPT => Error::ERROR_EA_FILE_CORRUPT,
        ERROR_EA_TABLE_FULL => Error::ERROR_EA_TABLE_FULL,
        ERROR_INVALID_EA_HANDLE => Error::ERROR_INVALID_EA_HANDLE,
        ERROR_EAS_NOT_SUPPORTED => Error::ERROR_EAS_NOT_SUPPORTED,
        ERROR_NOT_OWNER => Error::ERROR_NOT_OWNER,
        ERROR_TOO_MANY_POSTS => Error::ERROR_TOO_MANY_POSTS,
        ERROR_PARTIAL_COPY => Error::ERROR_PARTIAL_COPY,
        ERROR_OPLOCK_NOT_GRANTED => Error::ERROR_OPLOCK_NOT_GRANTED,
        ERROR_INVALID_OPLOCK_PROTOCOL => Error::ERROR_INVALID_OPLOCK_PROTOCOL,
        ERROR_DISK_TOO_FRAGMENTED => Error::ERROR_DISK_TOO_FRAGMENTED,
        ERROR_DELETE_PENDING => Error::ERROR_DELETE_PENDING,
        ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING => {
            Error::ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING
        }
        ERROR_SHORT_NAMES_NOT_ENABLED_ON_VOLUME => Error::ERROR_SHORT_NAMES_NOT_ENABLED_ON_VOLUME,
        ERROR_SECURITY_STREAM_IS_INCONSISTENT => Error::ERROR_SECURITY_STREAM_IS_INCONSISTENT,
        ERROR_INVALID_LOCK_RANGE => Error::ERROR_INVALID_LOCK_RANGE,
        ERROR_IMAGE_SUBSYSTEM_NOT_PRESENT => Error::ERROR_IMAGE_SUBSYSTEM_NOT_PRESENT,
        ERROR_NOTIFICATION_GUID_ALREADY_DEFINED => Error::ERROR_NOTIFICATION_GUID_ALREADY_DEFINED,
        ERROR_INVALID_EXCEPTION_HANDLER => Error::ERROR_INVALID_EXCEPTION_HANDLER,
        ERROR_DUPLICATE_PRIVILEGES => Error::ERROR_DUPLICATE_PRIVILEGES,
        ERROR_NO_RANGES_PROCESSED => Error::ERROR_NO_RANGES_PROCESSED,
        ERROR_NOT_ALLOWED_ON_SYSTEM_FILE => Error::ERROR_NOT_ALLOWED_ON_SYSTEM_FILE,
        ERROR_DISK_RESOURCES_EXHAUSTED => Error::ERROR_DISK_RESOURCES_EXHAUSTED,
        ERROR_INVALID_TOKEN => Error::ERROR_INVALID_TOKEN,
        ERROR_DEVICE_FEATURE_NOT_SUPPORTED => Error::ERROR_DEVICE_FEATURE_NOT_SUPPORTED,
        ERROR_MR_MID_NOT_FOUND => Error::ERROR_MR_MID_NOT_FOUND,
        ERROR_SCOPE_NOT_FOUND => Error::ERROR_SCOPE_NOT_FOUND,
        ERROR_UNDEFINED_SCOPE => Error::ERROR_UNDEFINED_SCOPE,
        ERROR_INVALID_CAP => Error::ERROR_INVALID_CAP,
        ERROR_DEVICE_UNREACHABLE => Error::ERROR_DEVICE_UNREACHABLE,
        ERROR_DEVICE_NO_RESOURCES => Error::ERROR_DEVICE_NO_RESOURCES,
        ERROR_DATA_CHECKSUM_ERROR => Error::ERROR_DATA_CHECKSUM_ERROR,
        ERROR_INTERMIXED_KERNEL_EA_OPERATION => Error::ERROR_INTERMIXED_KERNEL_EA_OPERATION,
        ERROR_FILE_LEVEL_TRIM_NOT_SUPPORTED => Error::ERROR_FILE_LEVEL_TRIM_NOT_SUPPORTED,
        ERROR_OFFSET_ALIGNMENT_VIOLATION => Error::ERROR_OFFSET_ALIGNMENT_VIOLATION,
        ERROR_INVALID_FIELD_IN_PARAMETER_LIST => Error::ERROR_INVALID_FIELD_IN_PARAMETER_LIST,
        ERROR_OPERATION_IN_PROGRESS => Error::ERROR_OPERATION_IN_PROGRESS,
        ERROR_BAD_DEVICE_PATH => Error::ERROR_BAD_DEVICE_PATH,
        ERROR_TOO_MANY_DESCRIPTORS => Error::ERROR_TOO_MANY_DESCRIPTORS,
        ERROR_SCRUB_DATA_DISABLED => Error::ERROR_SCRUB_DATA_DISABLED,
        ERROR_NOT_REDUNDANT_STORAGE => Error::ERROR_NOT_REDUNDANT_STORAGE,
        ERROR_RESIDENT_FILE_NOT_SUPPORTED => Error::ERROR_RESIDENT_FILE_NOT_SUPPORTED,
        ERROR_COMPRESSED_FILE_NOT_SUPPORTED => Error::ERROR_COMPRESSED_FILE_NOT_SUPPORTED,
        ERROR_DIRECTORY_NOT_SUPPORTED => Error::ERROR_DIRECTORY_NOT_SUPPORTED,
        ERROR_NOT_READ_FROM_COPY => Error::ERROR_NOT_READ_FROM_COPY,
        ERROR_FAIL_NOACTION_REBOOT => Error::ERROR_FAIL_NOACTION_REBOOT,
        ERROR_FAIL_SHUTDOWN => Error::ERROR_FAIL_SHUTDOWN,
        ERROR_FAIL_RESTART => Error::ERROR_FAIL_RESTART,
        ERROR_MAX_SESSIONS_REACHED => Error::ERROR_MAX_SESSIONS_REACHED,
        ERROR_THREAD_MODE_ALREADY_BACKGROUND => Error::ERROR_THREAD_MODE_ALREADY_BACKGROUND,
        ERROR_THREAD_MODE_NOT_BACKGROUND => Error::ERROR_THREAD_MODE_NOT_BACKGROUND,
        ERROR_PROCESS_MODE_ALREADY_BACKGROUND => Error::ERROR_PROCESS_MODE_ALREADY_BACKGROUND,
        ERROR_PROCESS_MODE_NOT_BACKGROUND => Error::ERROR_PROCESS_MODE_NOT_BACKGROUND,
        ERROR_INVALID_ADDRESS => Error::ERROR_INVALID_ADDRESS,
        _ => Error::UNKNOWN_ATTACH_ERROR(attach_result),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{thread::sleep, time::Duration};

    #[test]
    fn test_mount_vhd_read_only() {
        let mut vhd = Vhd::new(r"C:\Users\sam\dev\vhdrs\file.vhd", VhdType::Vhd);
        assert!(vhd.mount(MountMode::ReadOnly, false).is_ok());
        sleep(Duration::from_secs(5));
    }

    #[test]
    fn test_mount_vhd_read_write() {
        let mut vhd = Vhd::new(r"C:\Users\sam\dev\vhdrs\file.vhd", VhdType::Vhd);
        assert!(vhd.mount(MountMode::ReadWrite, false).is_ok());
    }
}
